apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: api
  labels:
    app: express-api
  annotations:
spec:
  selector:
    matchLabels:
      app: express-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
      - name: express-api
        image: thaddavis/nodejs:v13
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"