apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
  labels:
    app: express-api
spec:
  # type: LoadBalancer
  type: NodePort
  selector:
    app: express-api
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 5000