apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  namespace: db
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - protocol: TCP
      name: http
      port: 6000
      targetPort: 5432
  selector:
    app: postgres